version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: sh -c "cd note && yarn start"
    ports:
      - "3000:3000"
    stdin_open: true 